name       : haskell-persistent-sqlite
version    : 2.6.2
release    : 1
source     :
    - http://hackage.haskell.org/package/persistent-sqlite-2.6.2/persistent-sqlite-2.6.2.tar.gz : 6136c471fc81869cf0fde2049defb9c82698e3c0048d1321c3eda01046b985bf
license    : MIT
component  : programming.haskell
summary    : This package includes a thin sqlite3 wrapper based on the direct-sqlite package, as well as the entire C library, so there are no system dependencies.
description: |
    This package includes a thin sqlite3 wrapper based on the direct-sqlite package, as well as the entire C library, so there are no system dependencies.
builddeps  :
    - haskell-cabal-install
    - haskell-microlens-th
    - haskell-persistent
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
