name       : haskell-persistent-sqlite
version    : 2.8.1.2
release    : 2
source     :
    - http://hackage.haskell.org/package/persistent-sqlite-2.8.1.2/persistent-sqlite-2.8.1.2.tar.gz : 2f7157f3830370f60c7c36490ea49b7c52caf0f2a7349f86cf47970189f9ad0c
license    : MIT
component  : programming.haskell
summary    : This package includes a thin sqlite3 wrapper based on the direct-sqlite package, as well as the entire C library, so there are no system dependencies.
description: |
    This package includes a thin sqlite3 wrapper based on the direct-sqlite package, as well as the entire C library, so there are no system dependencies.
builddeps  :
    - haskell-cabal-install
    - haskell-microlens-th
    - haskell-persistent
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
