name       : haskell-persistent-sqlite
version    : 2.9.3
release    : 3
source     :
    - https://hackage.haskell.org/package/persistent-sqlite-2.9.3/persistent-sqlite-2.9.3.tar.gz : 985b9f7323e88f784ff93dd6f5bc65cb0183435dea052a5d238dec1e11b28b8f
license    : MIT
component  : programming.haskell
summary    : This package includes a thin sqlite3 wrapper based on the direct-sqlite package, as well as the entire C library, so there are no system dependencies.
description: |
    This package includes a thin sqlite3 wrapper based on the direct-sqlite package, as well as the entire C library, so there are no system dependencies.
builddeps  :
    - haskell-cabal-install
    - haskell-microlens-th-devel
    - haskell-persistent-devel
rundeps    :
    - devel:
        - haskell-microlens-th-devel
        - haskell-persistent-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
